version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: none
  http:
    container_name: http
    build:
      context: ..
      dockerfile: build/http.Dockerfile
    env_file:
      - ../.env
    depends_on:
      - rabbitmq
    restart: always
    ports:
      - 8000:8000
  simulations:
    container_name: simulations
    build:
      context: ..
      dockerfile: build/simulations.Dockerfile
    env_file:
      - ../.env
    depends_on:
      - rabbitmq
    restart: always
    deploy:
      mode: replicated
      replicas: 2
  worker:
    container_name: worker
    build:
      context: ..
      dockerfile: build/worker.Dockerfile
    env_file:
      - ../.env
    depends_on:
      - rabbitmq
      - cloud
    restart: always
    deploy:
      mode: replicated
      replicas: 5
  cloud:
    container_name: cloud_provider
    build:
      context: ..
      dockerfile: build/cloud.Dockerfile
    restart: always
    ports:
      - 50051:50051
    env_file:
      - ../.env
    deploy:
      mode: replicated
      replicas: 5