version: "3"
services:
  worker:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    ports:
      - 80:3000
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: challenge

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080